### ISSUE TITLE
music_vae_generate  not found 

### ISSUE THREAD

**Issue by ericosmic** [tensorflow/magenta#1309]
I tried to run music_vae model with pretrain model,  Ibut when I run the command script,  it is errer tip: music_vae_generate is not found .  I don't know what's wrong with it . I try to find solution on the internet, but there is not answer .   
this is my command script:
`music_vae_generate \
--config=cat-mel_2bar_big \
--checkpoint_file=pretrain_models/mel_2bar_big.ckpt \
--mode=sample \
--num_outputs=5 \
--output_dir=generate_results`

![2018-10-15 16-00-48](https://user-images.githubusercontent.com/35327931/46937400-c9d8d200-d093-11e8-91f0-f8fb935f0a57.png)

**Comment by adarob** [comment]
Which version of magenta do you have installed?

**Comment by ericosmic** [comment]
@adarob  sorry,    I don't know how to check the version of magenta , actually I just installed the magenta environment last week.

**Comment by adarob** [comment]
Try doing `pip install -U magenta` and see if it upgrades you to 0.3.12.

**Comment by ericosmic** [comment]
@adarob   I'm sure it had upgraded to 0.3.12,  but the same problem exist.  But  I could run the training script  (music_vae_train) successfully.

**Comment by adarob** [comment]
@ericosmic can you try uninstalling and re-installing it? You may also want to try uninstall with pip2 (or pip3) depending on which version of Python you want to keep.

**Comment by ericosmic** [comment]
I tried to run 'python music_vae_generate.py ' and addition config , before question is no more occor , but it would report the pretrain checkpoint not found ,  if I change the checkpoint path to the own training checkpoint , it all be ok . So I think the pretrain model maybe unnormal.

**Comment by adarob** [comment]
Please re-download the checkpoints. It should be fixed now.

**Comment by OSIA667** [comment]
hi, the checkpoint still can't be used. (music_vae_generate: command not found)
