### ISSUE TITLE
After installation / When I import magenta, I got TypeError: __init__() got an unexpected keyword argument 'openType'

### ISSUE THREAD

**Issue by JinSolChoi** [tensorflow/magenta#1409]
I'm using tensorflow-gpu version 1.12.0
After magenta installation, I got error when I did
`import magent` on python 2.7.12                                                                                                                                                                                          

The error was

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "build/bdist.linux-x86_64/egg/magenta/__init__.py", line 25, in <module>
>   File "build/bdist.linux-x86_64/egg/magenta/common/__init__.py", line 20, in <module>
>   File "build/bdist.linux-x86_64/egg/magenta/common/nade.py", line 23, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/__init__.py", line 78, in <module>
>     from tensorflow_probability.python import *  # pylint: disable=wildcard-import
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/python/__init__.py", line 21, in <module>
>     from tensorflow_probability.python import bijectors
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/python/bijectors/__init__.py", line 23, in <module>
>     from tensorflow_probability.python.bijectors.absolute_value import AbsoluteValue
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/python/bijectors/absolute_value.py", line 22, in <module>
>     from tensorflow_probability.python.bijectors import bijector
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/python/bijectors/bijector.py", line 31, in <module>
>     from tensorflow_probability.python.internal import distribution_util
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/python/internal/distribution_util.py", line 26, in <module>
>     from tensorflow_probability.python.internal import dtype_util
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/python/internal/dtype_util.py", line 24, in <module>
>     from tensorflow.contrib import framework as contrib_framework
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 39, in <module>
>     from tensorflow.contrib import cluster_resolver
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/cluster_resolver/__init__.py", line 23, in <module>
>     from tensorflow.contrib.cluster_resolver.python.training.cluster_resolver import ClusterResolver
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/cluster_resolver/python/training/__init__.py", line 24, in <module>
>     from tensorflow.contrib.cluster_resolver.python.training.gce_cluster_resolver import GceClusterResolver
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/cluster_resolver/python/training/gce_cluster_resolver.py", line 27, in <module>
>     from googleapiclient import discovery  # pylint: disable=g-import-not-at-top
>   File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 56, in <module>
>     from googleapiclient import _auth
>   File "/usr/local/lib/python2.7/dist-packages/googleapiclient/_auth.py", line 33, in <module>
>     import oauth2client.client
>   File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 54, in <module>
>     from oauth2client import crypt
>   File "/usr/local/lib/python2.7/dist-packages/oauth2client/crypt.py", line 27, in <module>
>     from oauth2client._pure_python_crypt import RsaSigner
>   File "/usr/local/lib/python2.7/dist-packages/oauth2client/_pure_python_crypt.py", line 24, in <module>
>     from pyasn1_modules.rfc2459 import Certificate
>   File "/usr/local/lib/python2.7/dist-packages/pyasn1_modules/rfc2459.py", line 1010, in <module>
>     class AttributeTypeAndValue(univ.Sequence):
>   File "/usr/local/lib/python2.7/dist-packages/pyasn1_modules/rfc2459.py", line 1014, in AttributeTypeAndValue
>     openType=opentype.OpenType('type', certificateAttributesMap))
> TypeError: __init__() got an unexpected keyword argument 'openType'

I saw someone got the similar error and they solved it through changing tensorflow version.
So I also downgraded tensorflow-gpu, but I got

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "build/bdist.linux-x86_64/egg/magenta/__init__.py", line 25, in <module>
>   File "build/bdist.linux-x86_64/egg/magenta/common/__init__.py", line 20, in <module>
>   File "build/bdist.linux-x86_64/egg/magenta/common/nade.py", line 23, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/__init__.py", line 68, in <module>
>     _ensure_tf_install()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/__init__.py", line 65, in _ensure_tf_install
>     present=tf.__version__))
> ImportError: This version of TensorFlow Probability requires TensorFlow version >= 1.12.0; Detected an installation of version 1.7.0. Please upgrade TensorFlow to proceed.

I tried tensorflow version 1.7, 1.8, 1.9, 1.10, 1.11
But the error was all same

I thought it's not the tensorflow version problem.
Please give me the solution.

**Comment by JinSolChoi** [comment]
Oh it was pyasn1 and pyasn1-modules version problem.
But there appeared so many RuntimeWarning.
When I try to import magenta again, I imported well.
But I want to solve this RuntimeWarning.

> /usr/local/lib/python2.7/dist-packages/sklearn/linear_model/base.py:35: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ..utils.seq_dataset import ArrayDataset, CSRDataset
/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/least_angle.py:23: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ..utils import arrayfuncs, as_float_array, check_X_y, deprecated
/usr/local/lib/python2.7/dist-packages/sklearn/utils/random.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._random import sample_without_replacement
/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/coordinate_descent.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import cd_fast
/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/__init__.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .sgd_fast import Hinge, Log, ModifiedHuber, SquaredLoss, Huber
/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/__init__.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .sgd_fast import Hinge, Log, ModifiedHuber, SquaredLoss, Huber
/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/sag.py:12: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .sag_fast import sag
/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py:8: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import libsvm, liblinear
/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py:8: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import libsvm, liblinear
/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py:9: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import libsvm_sparse
/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/__init__.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ball_tree import BallTree
/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/__init__.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ball_tree import BallTree
/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/__init__.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ball_tree import BallTree
/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/__init__.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .kd_tree import KDTree
/usr/local/lib/python2.7/dist-packages/sklearn/decomposition/online_lda.py:28: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._online_lda import (mean_change, _dirichlet_expectation_1d,
/usr/local/lib/python2.7/dist-packages/sklearn/utils/graph.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .graph_shortest_path import graph_shortest_path  # noqa
/usr/local/lib/python2.7/dist-packages/sklearn/isotonic.py:11: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._isotonic import _inplace_contiguous_isotonic_regression, _make_unique
/usr/local/lib/python2.7/dist-packages/sklearn/manifold/t_sne.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _utils
/usr/local/lib/python2.7/dist-packages/sklearn/manifold/t_sne.py:27: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _barnes_hut_tsne
/usr/local/lib/python2.7/dist-packages/sklearn/manifold/t_sne.py:27: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _barnes_hut_tsne
/usr/local/lib/python2.7/dist-packages/sklearn/tree/tree.py:40: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._criterion import Criterion
/usr/local/lib/python2.7/dist-packages/sklearn/tree/tree.py:40: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._criterion import Criterion
/usr/local/lib/python2.7/dist-packages/sklearn/tree/tree.py:40: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._criterion import Criterion
/usr/local/lib/python2.7/dist-packages/sklearn/tree/tree.py:40: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._criterion import Criterion
/usr/local/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:37: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _k_means
/usr/local/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py:38: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._k_means_elkan import k_means_elkan
/usr/local/lib/python2.7/dist-packages/sklearn/cluster/hierarchical.py:23: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hierarchical
/usr/local/lib/python2.7/dist-packages/sklearn/cluster/hierarchical.py:23: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hierarchical
/usr/local/lib/python2.7/dist-packages/sklearn/cluster/dbscan_.py:20: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._dbscan_inner import dbscan_inner
/usr/local/lib/python2.7/dist-packages/sklearn/feature_extraction/hashing.py:14: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._hashing import transform as _hashing_transform

**Comment by adarob** [comment]
According to https://github.com/numpy/numpy/issues/11788, upgrading your
numpy should fix it. Can you give that a try?

**Comment by JinSolChoi** [comment]
Hum I upgraded numpy version 1.14.5 to 1.16.0 but it still have a warning ;(

**Comment by adarob** [comment]
Luckily the warning isn't actually a problem so just ignore it for now. I'm hoping these will disappear once everyone moves to py3.
