### ISSUE TITLE
Can't run Onsets and Frames Colab notebook

### ISSUE THREAD

**Issue by yusuftas** [tensorflow/magenta#1625]
I'm not sure if I'm doing something wrong but I've just opened the onsets and frames colab notebook, but there are import issues.

```
---> 10 from magenta.models.onsets_frames_transcription import audio_label_data_utils
     11 from magenta.models.onsets_frames_transcription import configs
     12 from magenta.models.onsets_frames_transcription import constants

ImportError: cannot import name audio_label_data_utils
```

Same problem with any other imports from onsets_frames_transcription.

**Comment by cghawthorne** [comment]
Sorry about that. I think there's a mismatch between the notebook and some recent changes we made. A fixed version should be live on Monday or Tuesday.

**Comment by cghawthorne** [comment]
Should be fixed now!

**Comment by divisiondeariza** [comment]
Hey, it still has the same problem, I just checked this version and it's still failing.

https://colab.research.google.com/notebooks/magenta/onsets_frames_transcription/onsets_frames_transcription.ipynb

Also I think it's a good idea save the versions of the notebook into the repo, so everyone can see previous versions and maybe find when it broke.

Greetings

**Comment by divisiondeariza** [comment]
Solved adding this line just added this line before installing pyfluydsynth.

>  !apt-get install portaudio19-dev python-pyaudio python3-pyaudio

**Comment by cghawthorne** [comment]
Sorry about that, should be fixed now. In 270a9b94100270a673a69889b51c1f8b4132b22f, I removed the extra dependencies from the default magenta package setup that were causing the problems.
